In [42]:
import numpy as np

### **Função para_one_hot**

In [43]:
def para_one_hot(palavra):
    # Define o alfabeto a ser utilizado
    alfabeto = 'abcdefghijklmnopqrstuvwxyz!@#$%^&*()[}{];:",.<>/?\| '
    # Cria uma matriz de zeros com o tamanho do alfabeto e da palavra
    matriz = np.zeros((len(alfabeto), len(palavra)))
    # Converte a palavra para minúscula
    palavra = palavra.lower()
    # Loop para percorrer cada letra da palavra e preencher a matriz
    for i in range(len(palavra)):
        letra = palavra[i]
        indice = alfabeto.index(letra)
        matriz[indice][i] = 1
    return matriz


In [44]:
print(para_one_hot('abcdefghijklmnopqrstuvwxyz!@#$%^&*()[}{];:",.<>/?\| '))

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


### **Função para_string**

In [45]:
def para_string(matriz):
    # Define o alfabeto a ser utilizado
    alfabeto = 'abcdefghijklmnopqrstuvwxyz!@#$%^&*()[}{];:",.<>/?\| '
    # Cria uma variável para armazenar a palavra
    palavra = ''
    # Loop para percorrer cada coluna da matriz e preencher a palavra
    for i in range(matriz.shape[1]):
        indice = np.argmax(matriz[:, i])
        letra = alfabeto[indice]
        palavra += letra
    return palavra


In [46]:
print(para_string(para_one_hot('banana')))

banana


### **Função cifrar**

In [47]:
def cifrar(mensagem, P):
    # Converte a mensagem para one-hot
    matriz = para_one_hot(mensagem)
    # Multiplica a matriz pela matriz de permutação
    C = np.dot(P, matriz)
    return para_string(C)

In [48]:
# Define a matriz de permutação P
Mi = np.identity(52)
linhas = [i for i in range(52)]
np.random.shuffle(linhas)
Mp = Mi[linhas,:]

In [49]:
print(cifrar('highline quarta', Mp))

mkwmxk(@*fva$ba


### **Função de_cifrar**

In [50]:
def de_cifrar(mensagem, P):
    # Converte a mensagem para one-hot
    matriz = para_one_hot(mensagem) 
    # Multiplica a matriz pela inversa da matriz de permutação
    C = np.dot(np.linalg.inv(P),matriz)
    return para_string(C)

In [51]:
print(de_cifrar(cifrar('highline quarta', Mp), Mp))

highline quarta


### **Função enigma**

In [52]:
def enigma(mensagem, P, E):
    # Define o indice para percorrer a mensagem
    indice = 0
    # Define a variável para armazenar a mensagem cifrada
    resposta = ''
    # Loop para percorrer cada letra da mensagem
    for letra in mensagem:
        # Verifica se é a primeira letra
        if indice == 0:
            # Cifra a letra com a matriz de permutação P
            resposta += cifrar(letra, P)
        else:
            # Cifra a letra com a matriz de permutação P e a letra cifrada anteriormente com a matriz de permutação E quantas vezes for o indice
            letra_nova = cifrar(letra, P)
            for u in range(indice):
                letra_nova = cifrar(letra_nova,E)
            resposta += letra_nova
        indice += 1


    return resposta

In [53]:
# Define a matriz de permutação P e E
Mi = np.identity(52)
linhas = [i for i in range(52)]
np.random.shuffle(linhas)
Mp = Mi[linhas,:]
np.random.shuffle(linhas)
Me = Mi[linhas, :]

In [54]:
enigma('amata quinta',Mp,Me)

'/oo/.@noz&| '

### **Função de_enigma**

In [55]:
def de_enigma(mensagem, P, E):
    # Define o indice para percorrer a mensagem
    indice = 0
    # Define a variável para armazenar a mensagem cifrada
    resposta = ''
    # Loop para percorrer cada letra da mensagem
    for letra in mensagem:
        # Verifica se é a primeira letra e decifra a letra com a matriz de permutação P
        if indice == 0:
            letra = de_cifrar(letra, P)
            resposta += letra
        else:
            # Decifra a letra com a matriz de permutação P e a letra cifrada anteriormente com a matriz de permutação E quantas vezes for o indice
            for u in range(indice):
                letra = de_cifrar(letra,E)
            letra = de_cifrar(letra, P)
            resposta += letra
        indice += 1


    return resposta

In [56]:
de_enigma(enigma('amata quinta',Mp,Me), Mp, Me)

'amata quinta'