In [54]:
import numpy as np

### **Função para_one_hot**

In [55]:
def para_one_hot(palavra):
    alfabeto = 'abcdefghijklmnopqrstuvwxyz!@#$%^&*()[}{];:",.<>/?\| '
    matriz = np.zeros((len(alfabeto), len(palavra)))
    palavra = palavra.lower()
    for i in range(len(palavra)):
        letra = palavra[i]
        indice = alfabeto.index(letra)
        matriz[indice][i] = 1
    return matriz


In [56]:
print(para_one_hot('abcdefghijklmnopqrstuvwxyz!@#$%^&*()[}{];:",.<>/?\| '))

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


### **Função para_string**

In [57]:
def para_string(matriz):
    alfabeto = 'abcdefghijklmnopqrstuvwxyz!@#$%^&*()[}{];:",.<>/?\| '
    palavra = ''
    for i in range(matriz.shape[1]):
        indice = np.argmax(matriz[:, i])
        letra = alfabeto[indice]
        palavra += letra
    return palavra


In [58]:
print(para_string(para_one_hot('banana')))

banana


### **Função cifrar**

In [59]:
def cifrar(mensagem, P):
    matriz = para_one_hot(mensagem)
    C = np.dot(P, matriz)
    return para_string(C)

In [60]:
Mi = np.identity(52)
linhas = [i for i in range(52)]
np.random.shuffle(linhas)
Mp = Mi[linhas,:]

In [61]:
print(cifrar('highline quarta', Mp))

w#ywm#/tlgzj>$j


### **Função de_cifrar**

In [62]:
def de_cifrar(mensagem, P):
    matriz = para_one_hot(mensagem)
    C = np.dot(np.linalg.inv(P),matriz)
    return para_string(C)

In [63]:
print(de_cifrar(cifrar('highline quarta', Mp), Mp))

highline quarta


### **Função enigma**

In [64]:
def enigma(mensagem, P, E):
    indice = 0
    resposta = ''
    for letra in mensagem:
        if indice == 0:
            resposta += cifrar(letra, P)
        else:
            letra_nova = cifrar(letra, P)
            for u in range(indice):
                letra_nova = cifrar(letra_nova,E)
            resposta += letra_nova
        indice += 1


    return resposta

In [65]:
Mi = np.identity(52)
linhas = [i for i in range(52)]
np.random.shuffle(linhas)
Mp = Mi[linhas,:]
np.random.shuffle(linhas)
Me = Mi[linhas, :]

In [66]:
enigma('amata quinta',Mp,Me)

'@m)h\\),u}z;t'

### **Função de_enigma**

In [67]:
def de_enigma(mensagem, P, E):
    indice = 0
    resposta = ''
    for letra in mensagem:
        if indice == 0:
            letra = de_cifrar(letra, P)
            resposta += letra
        else:
            for u in range(indice):
                letra = de_cifrar(letra,E)
            letra = de_cifrar(letra, P)
            resposta += letra
        indice += 1


    return resposta

In [68]:
Mi = np.identity(52)
linhas = [i for i in range(52)]
np.random.shuffle(linhas)
Mp = Mi[linhas,:]
np.random.shuffle(linhas)
Me = Mi[linhas, :]

In [69]:
de_enigma(enigma('amata quinta',Mp,Me), Mp, Me)

'amata quinta'